# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails-async}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Bachman"]
  s.date = %q{2010-09-19}
  s.description = %q{Don't wait for your pages to render.}
  s.email = %q{adam.bachman@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/async_controller.rb",
     "app/helpers/async_helper.rb",
     "app/models/async_cache.rb",
     "config/routes.rb",
     "lib/async.rb",
     "lib/async/engine.rb",
     "rails-async.gemspec",
     "test/helper.rb",
     "test/test_async-rails.rb"
  ]
  s.homepage = %q{http://github.com/abachman/rails-async}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple async blocks.}
  s.test_files = [
    "test/helper.rb",
     "test/test_async-rails.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

